version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo
      - run:
          name: Installing G++
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install MAKE
          command: 'apt-get update && sudo apt-get install make'
      - run:
          name: Running test script..
          command: './testscript'
