version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          command: 'apt-get update && apt-get install -y sudo
      - run:
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          command: 'apt-get update && sudo apt-get install make'
      - run:
          command: './testscript'
